### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ###
### ONLY SPECIFIC FILES ###
### https://dev.to/eunit/how-to-automatically-deploy-from-github-git-to-cpanel-d36 ###
### ALL FILES ###
###  ###
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/philemmo/odi/
    - /bin/cp -R * $DEPLOYPATH
