<footer>
    <div class="container-fluid">
        <div class="row justify-content-evenly py-3">

            <div class="col-sm-2 px-2">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item fw-bold">Contact Info</li>
                    <li class="list-group-item">Phillip Emmons</li>
                    <li class="list-group-item">831.236.0849</li>
                    <li class="list-group-item">philemmons.now@gmail.com</li>
                </ul>
            </div>

            <div class="col-sm-2 px-2 text-center">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item fw-bold">Hours & Location</li>
                    <li class="list-group-item">9am to 5pm PST</li>
                    <li class="list-group-item">Monday to Friday</li>
                    <li class="list-group-item">Marina, CA</li>
                </ul>
            </div>

            <div class="col-sm-2 px-2">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Accessibility</li>
                    <li class="list-group-item">Terms of Service</li>
                    <li class="list-group-item">Privacy Policy</li>
                    <li class="list-group-item">FAQs</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container bg-dark-blue py-3">
        <div class="row">
            <div class="col-sm-12 text-center text-white fs-7">
                <p class="pt-1">© 2025 OnDemand IT | All Right Reserved. | Powered by Caffeine.
                </p>
            </div>
        </div>
    </div>
    </div>
</footer>