<footer class="container">

    <div class="row py-6 px-5">

        <div class="col-sm-4">
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-uppercase fw-bold">Contact</li>
                <li class="list-group-item">Phillip Emmons</li>
                <li class="list-group-item">831.236.0849</li>
                <li class="list-group-item">admin@philemmons.dev</li>
            </ul>
        </div>

        <div class="col-sm-4">
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-uppercase fw-bold">Hours of Operation</li>
                <li class="list-group-item">Monday to Friday</li>
                <li class="list-group-item">9am to 5pm PST</li>
                <li class="list-group-item">Marina, CA</li>
            </ul>
        </div>

        <div class="col-sm-4">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Accessibility</li>
                <li class="list-group-item">Terms of Service</li>
                <li class="list-group-item">Privacy Policy</li>
                <li class="list-group-item">FAQs</li>
            </ul>
        </div>

        <div class="col-sm-12 text-center">
            <p>© 2025 OnDemand IT | All Right Reserved. | Powered by Caffeine.
            </p>
        </div>

    </div>
</footer>