<footer>
    <div class="container py-5">
        <div class="row justify-content-evenly text-center">
            <div class="col-lg-3 py-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item p-0">Phillip Emmons</li>
                    <li class="list-group-item p-0">831.236.0849</li>
                    <li class="list-group-item p-0">philemmons.now@gmail.com</li>
                </ul>
            </div>
            <div class="col-lg-2 py-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item p-0">9am to 5pm PST</li>
                    <li class="list-group-item p-0">Monday to Friday</li>
                    <li class="list-group-item p-0">Marina, CA</li>
                </ul>
            </div>


            <div class="col-lg-2 py-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item p-0">Accessibility</li>
                    <li class="list-group-item p-0">Terms of Service</li>
                    <li class="list-group-item p-0">Privacy Policy</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container bg-dark-blue py-3">
        <div class="row">
            <div class="col-sm-12 text-center text-white fs-7">
                <p class="pt-1">© 2025 OnDemand IT  |  All Right Reserved.  |  Powered by Caffeine.
                </p>
            </div>
        </div>
    </div>

</footer>