    <meta name="description" content="Experienced in web development and maintenance, creating WCAG 2.1-compliant, usable, secure, user-focused websites.">
    <meta name="author" content="philemmons.dev">

    <!-- social media tags -->
    <meta property="og:title" content="Website Design | OnDemand IT">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://on-demand.philemmons.dev/">
    <meta property="og:description" content="OnDemand IT Services delivers expert tech support, SEO-optimized websites, and powerful online surveys—helping your business run smarter, faster.">
    <meta property="og:image" content="/images/one-zero.jpg">

    <!-- twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="on-demand.philemmons.dev">
    <meta property="twitter:url" content="https://on-demand.philemmons.dev/">
    <meta name="twitter:title" content="Website Design | OnDemand IT">
    <meta name="twitter:description" content="OnDemand IT Services delivers expert tech support, SEO-optimized websites, and powerful online surveys—helping your business run smarter, faster.">
    <meta name="twitter:image" content="/images/one-zero.jpg">


    <link rel="icon" href="/images/icons/favicon.ico">
    <link rel="apple-touch-icon" href="/images/icons/apple-touch-icon.png">

    <link rel="stylesheet" href="css/styles.css">

    <!-- bootstrap CSS v5.3.5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>